name: font_gallery
description: An app which showcases the different fonts
publish_to: 'none'
version: 1.3.0+7

environment:
  sdk: ^3.7.0
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/